# Generated by Django 5.1.7 on 2025-03-08 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_source', models.BooleanField(default=True, help_text='Can be used as source')),
                ('is_target', models.BooleanField(default=True, help_text='Can be used as target')),
                ('informatica_type', models.CharField(help_text='Connector type in Informatica', max_length=100)),
                ('category', models.CharField(choices=[('DATABASE', 'Database'), ('FILE', 'File'), ('CLOUD', 'Cloud Service'), ('MESSAGING', 'Messaging'), ('BIGDATA', 'Big Data'), ('API', 'API/Web Service')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformaticaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_config', models.JSONField(help_text='Non-sensitive configuration details')),
                ('credentials', models.JSONField(blank=True, help_text='Encrypted sensitive credentials', null=True)),
                ('informatica_connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica_services.connectortype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('MAPPING', 'Data Mapping'), ('CODE', 'Code Task'), ('FILE_TRANSFER', 'File Transfer'), ('DYNAMIC_MAPPING', 'Dynamic Mapping')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('task_config', models.JSONField(help_text='Task configuration details')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tasks', to='informatica_services.informaticaconnection')),
                ('target_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_tasks', to='informatica_services.informaticaconnection')),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('input_params', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('informatica_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='informatica_services.datatask')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_key', models.CharField(help_text='Key used in configuration', max_length=100)),
                ('field_type', models.CharField(choices=[('STRING', 'Text String'), ('PASSWORD', 'Password'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('FILE', 'File Upload'), ('SELECT', 'Selection'), ('MULTISELECT', 'Multiple Selection')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_credential', models.BooleanField(default=False, help_text='Whether this field contains sensitive data')),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, help_text='Regex for field validation', max_length=500)),
                ('options', models.JSONField(blank=True, help_text='Options for SELECT/MULTISELECT fields', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in forms')),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='informatica_services.connectortype')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('connector_type', 'field_key')},
            },
        ),
    ]
