# Generated by Django 5.1.7 on 2025-03-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_last_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informaticacredentials',
            name='user',
        ),
    ]
