# Generated by Django 5.1.7 on 2025-03-08 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('component_type', models.CharField(choices=[('INPUT', 'Input Component'), ('PROCESS', 'Processing Component'), ('OUTPUT', 'Output Component'), ('DECISION', 'Decision Component')], max_length=50)),
                ('configuration_schema', models.JSONField(help_text='JSON schema for component configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(help_text='X coordinate in the workflow canvas')),
                ('position_y', models.FloatField(help_text='Y coordinate in the workflow canvas')),
                ('configuration', models.JSONField(help_text='Component specific configuration')),
                ('order', models.IntegerField(help_text='Execution order in the workflow')),
                ('ai_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.aicomponent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='workflow_engine.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComponentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('SUCCESS', 'Success Path'), ('FAILURE', 'Failure Path'), ('CONDITIONAL', 'Conditional Path')], max_length=50)),
                ('condition', models.JSONField(blank=True, help_text='Conditions for conditional paths', null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflow_engine.workflow')),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflow_engine.workflowcomponent')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflow_engine.workflowcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow_engine.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('workflow_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.workflowcomponent')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_logs', to='workflow_engine.workflowexecution')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
